### ISSUE TITLE
Move `index.js` into root

### ISSUE THREAD

**Issue by deadcoder0904** [marudy/react-native-responsive-screen#1]
It really feels unnecessary to go into another folder to just view 1 file :(

**Comment by marudy** [comment]
Yes you are absolutely right! I plan to do it very very soon and also put the time to create example repositories as you already suggested :)

I will update the issue here when it's done.

**Comment by marudy** [comment]
@deadcoder0904 it's done and available in `master` branch! Published in npm as well :D

**Comment by deadcoder0904** [comment]
I really want to try it for https://github.com/deadcoder0904/react-native-tablets but seriously I don't have time right now. And the current solution just works fine so I'll take a look soonish ;)

**Comment by marudy** [comment]
Please go ahead and try it when you get the chance :) I have tested the logic of this package in tablets  within my first big RN application and I was pretty happy with the result. 

The key is to always use the 2 exposed methods (`heightPercentageToDP`, `widthPercentageToDP`) instead of DP even for things like `font-size` or `border-width`. These are the cases that you could see differences when screen size changes significantly (besides the standard `width`, `height` properties).

**Comment by deadcoder0904** [comment]
What about a use-case where we make use of Smaller Size than the Size we coded on.

That is one issue with the library I am using. See https://github.com/nirsky/react-native-size-matters/issues/4

In short - If I use this package on `700dp` screen & then I open the app on `400dp` screen will it work properly or do I have to change anything❓

That's the only issue I have with `react-native-size-matters`. So I start with the smallest screen & then go all the way up.

**Comment by marudy** [comment]
OK I see. 

You will not have this type of issue with `react-native-responsive-screen` package. But you need to forget of supplying DP as input to your CSS and let the package apply the correct DP for you. You should start thinking in percentages if you are to use this package. If this is clear, then you will be fine. 

Because if you do `width: ${widthPercentage('60%')}` let's say in a box, the box will get 60% of the screen's width for every different screen size. The package calculates dynamically the screen's dimensions when app is initialized (and optionally can adopt to orientation changes).

**Comment by deadcoder0904** [comment]
Wow I would totally appreciate it. Maybe make a branch since I've written a [blog post](https://medium.com/react-native-training/scaling-react-native-apps-for-tablets-211de8399cf1) on that topic & so I cannot change the master branch.

If you don't mind then a PR with another branch `dev` would be great 😜

If your package works well enough, I will definitely add it to that article if its allowed or write a new one for you since your package is much simpler to use 😃

**Comment by deadcoder0904** [comment]
Also, if you can come up with small names like `wp` & `hp` rather than these big ones it would be helpful or just add it to the `README` so people don't get scared -

```js
import { 
       widthPercentageToDP as wp, 
       heightPercentageToDP as hp 
} from 'react-native-responsive-screen';
```

**Comment by deadcoder0904** [comment]
Also, your `styled-components` example has a small bug

```js
import styled from 'styled-components/native';
```

must be

```js
import styled from 'styled-components';
```

since the API changed after 3.0 release

**Comment by deadcoder0904** [comment]
Another error -

```js
const Login = styled.Text`
  font-size: heightPercentageToDP('5%') // End result looks like the provided UI mockup
`;
```

must be

```js
const Login = styled.Text`
  font-size: ${heightPercentageToDP('5%')} // End result looks like the provided UI mockup
`;
```

**Comment by marudy** [comment]
Yes, I can create a new `dev` branch and then you see how you take it from there. If you like the result, I would totally appreciate a blog post mention :smile: I will do that during the weekend - more free time :))

Thanks a lot for mentioning the errors. Regarding the `import styled from 'styled-components/native';` it works fine but maybe it's obsolete after version 3.0? Will check it out and correct it. Finally, regarding the big names you are totally right about being scary... Maybe I will do something like what you propose!

**Comment by marudy** [comment]
Hey @deadcoder0904,

I added an `examples` folder with 3 sample repositories inside :) I also corrected the wrong documentation you pointed out about `styled-components` import and usage in `README.md`. And published a new version 1.1.2 with these changes/additions. Have a look if you have the time for some feedback :smiley: 

During the weekend I will definitely get up to speed with your project as discussed :D and maybe change the method names to smaller

**Comment by deadcoder0904** [comment]
Looks nice but I have yet another feedback.

README looks too big for such a small thing. So maybe move, `styled-components` example in a `styled-components/README.md` file so that those who don't use it don't need to see it.

Also, the examples folder can have their own README or another GIF to make it look better (do this only if you have free time).

Keep the README focused & short & show links with `styled-components`, `orientation` to another files.

And reduce the code. Checkout [Size Matters](https://github.com/nirsky/react-native-size-matters) README. The code is extremely short. You don't need `import` statements other than your packages `import`. You don't need `styles` object, just make it inline.

Make that README as small as Size Matters because its too overwhelming that's why I didn't start 😂

You can also add API section or Table Of Contents at start so its easier to navigate like https://awesome.re

**Comment by marudy** [comment]
I like the feedback you provided to me, thanks.

I will try to implement a few of them over the next days. I also want want to create and publish a couple more packages over the upcoming weeks, so it's nice thqt i get the feedback early!
