### ISSUE TITLE
Renders behind android virtual buttons.

### ISSUE THREAD

**Issue by i-mighty** [marudy/react-native-responsive-screen#18]
I'm using an Android 7.1 smart phone and if I set the height to 100%, the view renders behind the virtual buttons, making it impossible to access components at the button of the view.
Please i would like to know iif I am the only person experiencing this and what I can do.
Thanks a lot in advance.

**Comment by marudy** [comment]
Hey there @i-mighty,

I am trying to understand the problem. When you say virtual buttons what do you mean exactly? Emulator buttons or your app's buttons? Also you mean the problem is in the bottom, not button right?

My guess is that some part of the UI is absolute and simply hides behind.
