### ISSUE TITLE
Not exact at all

### ISSUE THREAD

**Issue by urlchange** [marudy/react-native-responsive-screen#19]
Hi, first of all thanks for the package.

I just downloaded it and I made a simple layout with 2 boxes, each of them 50% of the screen and then I placed an image in each of the boxes.

```
import React, { Component } from 'react';
import { StyleSheet, View, Image } from 'react-native';
import {
    widthPercentageToDP as wp,
    heightPercentageToDP,
    listenOrientationChange as loc,
    removeOrientationListener as rol
} from 'react-native-responsive-screen';

class Tetset extends Component {

    componentDidMount() {
        loc(this);
    }

    componentWillUnMount() {
        rol();
    }

    render() {

        const styles = StyleSheet.create({
            viewContainer: {
                flex: 1,
            },
            childContainer1: {
                backgroundColor: 'blue',
                height: heightPercentageToDP('50%')
            },
            childContainer2: {
                backgroundColor: 'red',
                height: heightPercentageToDP('50%')
            }
        });

        return (
            <View style={[styles.viewContainer]}>
                <View style={[styles.childContainer1]}>
                    <Image
                        source={require('../../img/cj.png')}
                    />
                </View>
                <View style={[styles.childContainer2]}>
                    <Image
                        source={require('../../img/cj.png')}
                    />
                </View>
            </View>
        );
    }
}

export default Tetset;
```

After running the app, one of the images looks more cropped from the bottom than the other, that means the boxes aren't the same size. Is there any reason for this behavior?

Here a screenshot:
![screenshot_1548636099](https://user-images.githubusercontent.com/34321091/51809166-0a083d00-229e-11e9-9989-a620e7c511c9.png)

I tested it on a physical Xiaomi Mi A1 and on a virtual Nexus 5X with the same result.
Thanks in advance.

**Comment by marudy** [comment]
Hey bud. A few from my side:
1. StyleSheet.create should be outside the class and specifically the render method. Because the styles will be created every time there is a re-render.
2. In the specific image the problem should be because of the virtual keyboard at the bottom.
3. For 50% - 50% screen split you can use flex as well

**Comment by marudy** [comment]
Hey @urlchange,

any update at this? did you find a way to solve it?
