### ISSUE TITLE
this.setState this is undefined on orientation change

### ISSUE THREAD

**Issue by ManalLiaquat** [marudy/react-native-responsive-screen#26]
undefined is not an object (evaluating 'that.setState')
<unknown>
    
emit
    
set
    
<unknown>
    D:\manal\reactnative\new\FOODISTAN\node_modules\react-native\Libraries\Components\ScrollView\ScrollView.js:808:8
emit
    
__callFunction
    D:\manal\reactnative\new\FOODISTAN\node_modules\react-native\Libraries\ART\ReactNativeART.js:391:6
<unknown>
    
__guard
    D:\manal\reactnative\new\FOODISTAN\node_modules\react-native\Libraries\ART\ReactNativeART.js:347:9
callFunctionReturnFlushedQueue
    

```
componentDidMount = () => {
    loc();
  };

  componentWillUnmount = () => {
    rol();
  };
[...]
<TouchableOpacity
                        key={i}
                        onPress={() => {
                          this.setState({ currentTab: i + 1 });
                        }}
                      >
                        <Text
           
                        >
                          text
                        </Text>
</TouchableOpacity>
```

**Comment by AhmedMKamal** [comment]
Hi @ManalLiaquat, you have to pass the component class to `loc` function.

```
componentDidMount = () => {
    loc(this); // like this...
  };

  componentWillUnmount = () => {
    rol();
  };
[...]
<TouchableOpacity
                        key={i}
                        onPress={() => {
                          this.setState({ currentTab: i + 1 });
                        }}
                      >
                        <Text
           
                        >
                          text
                        </Text>
</TouchableOpacity>
```

**Comment by ManalLiaquat** [comment]
Thank for earlier response, I forgot to see `this` keyword in the documentation.
