### ISSUE TITLE
Not working on smaller/old devices 

### ISSUE THREAD

**Issue by Muhammad-Iqbal** [marudy/react-native-responsive-screen#27]
Hi, there thanks for this package it solved my 80% problem

Currently, I am using it for calculator keyboard layout. it worked perfectly on all the devices expect iPhone 5s,iPhone SE and iPad 2 

![Simulator Screen Shot - iPad 2 - 2019-04-02 at 20 18 58](https://user-images.githubusercontent.com/19371570/55475031-40f72800-562c-11e9-93ad-ad5f8cec55fa.png)

**Comment by jdnichollsc** [comment]
So what's the problem here?

**Comment by marudy** [comment]
Hey @Muhammad-Iqbal, @jdnichollsc and sorry for the late response. And happy new year!

I use the package normally in iPhone 5s and other old Android devices for quite long time already. Did you try to debug to see where the issue occurs?

Thanks

**Comment by marchiartur** [comment]
![responsividade](https://user-images.githubusercontent.com/46831047/130971033-58b9ac3b-9e4f-4fdf-934b-7f8fb415b4ca.png)

the responsibility is not working on a redmi device
