### ISSUE TITLE
Round image with wp y hp

### ISSUE THREAD

**Issue by georgeMorales** [marudy/react-native-responsive-screen#30]
How could I generate a round image with wp and hp, what value of borderRadius with wp ('15% ') and hp ('15%')?

**Comment by nicoache1** [comment]
@JorgeMoralesLopez  You should use the same method for every property.
`borderRadius: heightPercentageToDP(10) / 2,`
`height: heightPercentageToDP(10),`
`width: heightPercentageToDP(10),`

**Comment by marudy** [comment]
@georgeMorales yeah exactly as @nicoache1 mentioned.
