### ISSUE TITLE
Does not support external Stylesheets

### ISSUE THREAD

**Issue by OdderOwl** [marudy/react-native-responsive-screen#31]
I have been using this in my project and it has been a great help so far. One thing I have noticed though is that it does not seem to support external Stylesheets.

I figured out that width and height are not re-calculated after orientation change when you use external stylesheets, so the sizes are not accurate in one orientation, but perfectly fine for the other orientation. 

I fixed this by putting the creation of the Stylesheets inside the render function as the examples suggest. While this works perfectly fine now, my code has become pretty long and messy since i have lots of styles. So I would prefer if it could work with external stylesheets.
Is this possible?

I could not come up with a better solution on my own yet but I will try as well when I have more time in the upcoming days.

**Comment by gams95** [comment]
Hi, i have actually implement it in external Stylesheets by importing the component in an external stylesheet file. Can you share your code?

**Comment by OdderOwl** [comment]
no sorry, I cant share it. But I loaded it in my stylesheet file yet the listener for orientation change was not triggered and I dont know how to fix it except having styles in the same file :(

**Comment by gams95** [comment]
U can set the style outside however set the height and width in the main
component

**Comment by OdderOwl** [comment]
did what gams suggested (thx dude <3 ) looks good enough now so im gonna close this issue
