### ISSUE TITLE
react-native-responsive-screen don't work in ios release version

### ISSUE THREAD

**Issue by MorgadoKnivet** [marudy/react-native-responsive-screen#38]
Hello People. I have a problem with react-native-responsive-screen. When run debug IOS version, my styles are working nice, but, in production, don't work. Don't return a value. Could help me with issue? Thanks

 "react-native": "0.60.5",
 "react-native-responsive-screen": "^1.2.2",

Screenshots - Prod / Debug

![Screen Shot 2019-10-24 at 22 39 10](https://user-images.githubusercontent.com/34779500/67536833-5195eb00-f6af-11e9-8d6f-5f08289925ad.png)
![Screen Shot 2019-10-24 at 22 41 03](https://user-images.githubusercontent.com/34779500/67536850-64102480-f6af-11e9-99f8-b6505f814416.png)

**Comment by marudy** [comment]
Hey @MorgadoKnivet and sorry for the late response. Happy new year!

I can confirm that this is not an issue related with DEV / PROD versions. I use the package normally in version 0.60.5 as well. Also the package is pure JavaScript, doesn't require any linking to work. Maybe it's not installed / imported properly in production build?
